# Generated by Django 2.1 on 2018-09-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время добавления', verbose_name='Время добавления')),
                ('title', models.CharField(help_text='Название страницы', max_length=150, verbose_name='Название страницы')),
                ('slug', models.CharField(blank=True, help_text='Url страницы', max_length=250, verbose_name='Url страницы')),
                ('status', models.BooleanField(default=False, help_text='Статус активна/скрыта', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
