version: '3'

services:

  runserver:
    command: .bin/run.sh
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=asdasd5!22434%66744dfsdfssdfs!s9ssdj
      - POSTGRES_NAME=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - TZ=Europe/Moscow

  autotests:
    command: .bin/run-autotests.sh
    environment:
      - SECRET_KEY=asdasd5!22434%66744dfsdfssdfs!s9ssdj
      - POSTGRES_NAME=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - TZ=Europe/Moscow

  postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    ports:
      - 5432:5432

  celery:
    command: .bin/run-celery.sh
    privileged: true
    environment:
      - SECRET_KEY=asdasd5!22434%66744dfsdfssdfs!s9ssdj
      - POSTGRES_NAME=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - TZ=Europe/Moscow